# Generated by Django 5.2.6 on 2025-12-26 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('Branch_Code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Branch_Name', models.CharField(max_length=255)),
                ('Stream', models.CharField(max_length=255)),
                ('Degree_Type', models.CharField(max_length=50)),
                ('Duration_Years', models.PositiveSmallIntegerField(default=4)),
                ('Is_Core_Branch', models.BooleanField(default=False)),
                ('Is_Emerging_Branch', models.BooleanField(default=False)),
                ('Popularity_Rank', models.PositiveIntegerField(blank=True, null=True)),
                ('Demand_Score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('Is_Active', models.BooleanField(default=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=10, unique=True)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('reservation_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_eligibility_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_general', models.BooleanField(default=False)),
                ('is_reserved', models.BooleanField(default=True)),
                ('demand_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('priority_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('College_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('College_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('approvals', models.CharField(max_length=255)),
                ('naaccrating', models.CharField(max_length=255)),
                ('firstyearfees', models.CharField(max_length=255)),
                ('averagepackage', models.CharField(max_length=255)),
                ('highestpackage', models.CharField(max_length=255)),
                ('Rating', models.CharField(max_length=255)),
                ('nationalrank', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_code', models.CharField(max_length=20, unique=True)),
                ('round_name', models.CharField(blank=True, max_length=50)),
                ('competition_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cutoff_relaxation_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'round',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_code', models.PositiveSmallIntegerField(unique=True)),
                ('year_label', models.CharField(blank=True, max_length=10)),
                ('competition_index', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'year_dim',
            },
        ),
        migrations.CreateModel(
            name='CollegeBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_branch', models.CharField(editable=False, max_length=50, unique=True)),
                ('branch', models.ForeignKey(db_column='Branch_Code', on_delete=django.db.models.deletion.CASCADE, related_name='branch_colleges', to='core.branch')),
                ('college', models.ForeignKey(db_column='College_code', on_delete=django.db.models.deletion.CASCADE, related_name='college_branches', to='core.college')),
            ],
            options={
                'db_table': 'college_branch',
                'unique_together': {('college', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('college_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='core.collegebranch')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.year')),
            ],
            options={
                'unique_together': {('college_branch', 'category', 'round', 'year')},
            },
        ),
    ]
