# Generated by Django 4.2.10 on 2026-01-20 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovedGmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'approved_gmails',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('Branch_Code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Branch_Name', models.CharField(max_length=255)),
                ('Stream', models.CharField(max_length=255)),
                ('Degree_Type', models.CharField(max_length=50)),
                ('Duration_Years', models.PositiveSmallIntegerField(default=4)),
                ('Is_Core_Branch', models.BooleanField(default=False)),
                ('Is_Emerging_Branch', models.BooleanField(default=False)),
                ('Popularity_Rank', models.PositiveIntegerField(blank=True, null=True)),
                ('Demand_Score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('Is_Active', models.BooleanField(default=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=10, unique=True)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('reservation_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_eligibility_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_general', models.BooleanField(default=False)),
                ('is_reserved', models.BooleanField(default=True)),
                ('demand_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('priority_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('College_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('approvals', models.CharField(max_length=255)),
                ('naaccrating', models.CharField(max_length=255)),
                ('firstyearfees', models.FloatField(max_length=255)),
                ('averagepackage', models.FloatField(max_length=255)),
                ('highestpackage', models.FloatField(max_length=255)),
                ('Rating', models.FloatField(max_length=255)),
                ('nationalrank', models.IntegerField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_branch', models.CharField(editable=False, max_length=50, unique=True)),
                ('branch', models.ForeignKey(db_column='Branch_Code', on_delete=django.db.models.deletion.CASCADE, related_name='branch_colleges', to='core.branch')),
                ('college', models.ForeignKey(db_column='college_code', on_delete=django.db.models.deletion.CASCADE, related_name='college_branches', to='core.college')),
            ],
            options={
                'db_table': 'college_branch',
                'unique_together': {('college', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_code', models.CharField(max_length=20, unique=True)),
                ('round_name', models.CharField(blank=True, max_length=50)),
                ('competition_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cutoff_relaxation_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'round',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscribers',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_code', models.PositiveSmallIntegerField(unique=True)),
                ('year_label', models.CharField(blank=True, max_length=10)),
                ('competition_index', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'year_dim',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('ADMIN', 'Admin'), ('MODERATOR', 'Moderator')], default='STUDENT', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_question', models.TextField()),
                ('bot_answer', models.TextField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('entities', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'chat_logs',
                'indexes': [models.Index(fields=['timestamp'], name='chat_logs_timesta_433c6b_idx'), models.Index(fields=['intent'], name='chat_logs_intent_91efc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeatMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.PositiveIntegerField()),
                ('filled_seats', models.PositiveIntegerField(default=0)),
                ('available_seats', models.PositiveIntegerField(editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('college_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collegebranch')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.year')),
            ],
            options={
                'db_table': 'seat_matrix',
                'unique_together': {('college_branch', 'year', 'category', 'round')},
            },
        ),
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('college_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='core.collegebranch')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.year')),
            ],
            options={
                'unique_together': {('college_branch', 'category', 'round', 'year')},
            },
        ),
    ]
