# Generated by Django 5.2.6 on 2025-12-26 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.PositiveIntegerField()),
                ('filled_seats', models.PositiveIntegerField(default=0)),
                ('available_seats', models.PositiveIntegerField(editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('college_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collegebranch')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.round')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.year')),
            ],
            options={
                'db_table': 'seat_matrix',
                'unique_together': {('college_branch', 'year', 'category', 'round')},
            },
        ),
    ]
