# Generated by Django 5.2.6 on 2025-12-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seatmatrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedGmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'approved_gmails',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscribers',
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_question', models.TextField()),
                ('bot_answer', models.TextField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('entities', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'chat_logs',
                'indexes': [models.Index(fields=['timestamp'], name='chat_logs_timesta_433c6b_idx'), models.Index(fields=['intent'], name='chat_logs_intent_91efc1_idx')],
            },
        ),
    ]
