# Generated by Django 5.2.6 on 2025-12-30 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='College_code',
            new_name='college_code',
        ),
        migrations.AlterField(
            model_name='collegebranch',
            name='college',
            field=models.ForeignKey(db_column='college_code', on_delete=django.db.models.deletion.CASCADE, related_name='college_branches', to='core.college'),
        ),
    ]
