# Generated by Django 5.2.6 on 2026-01-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_college_code_college_college_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='Rating',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='averagepackage',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='firstyearfees',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='highestpackage',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='nationalrank',
            field=models.IntegerField(max_length=255),
        ),
    ]
