# Generated by Django 5.2.6 on 2026-01-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_college_rating_alter_college_averagepackage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='nationalrank',
            field=models.FloatField(max_length=255),
        ),
    ]
