# Generated by Django 5.2.6 on 2026-01-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_college_nationalrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='nationalrank',
            field=models.IntegerField(max_length=255),
        ),
    ]
