# Generated by Django 5.2.6 on 2026-01-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_college_nationalrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='nationalrank',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
